#!/usr/bin/env python3
"""Per-cell hyperparameter screen results, as a LaTeX appendix table.

Zimeng's note on the draft: the paper says sixteen configurations were
searched but shows no per-cell outcome, and a search cannot be claimed
without one. This emits every cell.

Each variant is paired against the control on the identical (panel, seed)
cells it shares, which is how the screen's decision rule was defined, so
the reported t is a paired t over 6 cells rather than a two-sample
comparison of noisy means.

    python3 hp_appendix_table.py
"""
import csv
import math
import os
from collections import defaultdict

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "results_econ", "hp_screen_score.csv")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(HERE))),
                   "paper", "hp_screen_table.tex")

LABEL = {
    "hp_C0": "C0 (control)",
    "hp_W1_S1_icgated": "Selection: gated rank IC",
    "hp_W1_S2_ic": "Selection: rank IC",
    "hp_W1_T1_cs5": "Target: 5-day horizon",
    "hp_W1_TS_cs5_icg": "Target 5-day + gated",
    "hp_W2_R1_e5g10": "Elite 5 / generated 10",
    "hp_W2_R2_e5g15": "Elite 5 / generated 15",
    "hp_W2_F1_repop25": "Repopulation every 25",
    "hp_W2_F2_repop100": "Repopulation every 100",
    "hp_W2_N1_nts600": "600 train subseq.",
    "hp_W2_G1_rounds2": "2 generations / window",
    "hp_W3_P1_pa04": "Replay $\\alpha=0.4$",
    "hp_W3_P2_pa08": "Replay $\\alpha=0.8$",
    "hp_W3_P3_pl021": "Replay $\\lambda=0.021$",
    "hp_W3_P0_uniform": "Replay off (uniform)",
    "hp_W3_B1_bp20": "20 backprop.\\ epochs",
}
ORDER = ["hp_C0", "hp_W1_S1_icgated", "hp_W1_S2_ic", "hp_W1_T1_cs5",
         "hp_W1_TS_cs5_icg", "hp_W2_R1_e5g10", "hp_W2_R2_e5g15",
         "hp_W2_F1_repop25", "hp_W2_F2_repop100", "hp_W2_N1_nts600",
         "hp_W2_G1_rounds2", "hp_W3_P1_pa04", "hp_W3_P2_pa08",
         "hp_W3_P3_pl021", "hp_W3_P0_uniform", "hp_W3_B1_bp20"]


def paired_t(d):
    d = np.asarray([x for x in d if x == x], dtype=float)
    if len(d) < 2:
        return float("nan"), float("nan")
    sd = d.std(ddof=1)
    if sd == 0:
        return float(d.mean()), float("inf")
    return float(d.mean()), float(d.mean() / (sd / math.sqrt(len(d))))


def main():
    cells = defaultdict(dict)
    for r in csv.DictReader(open(SRC)):
        try:
            cells[r["arm"]][(r["panel"], r["seed"])] = (
                float(r["rank_ic"]), float(r["net_pct"]), float(r["sharpe"]))
        except ValueError:
            continue

    ctrl = cells["hp_C0"]
    rows = []
    for arm in ORDER:
        if arm not in cells:
            continue
        v = list(cells[arm].values())
        ic = float(np.mean([x[0] for x in v]))
        net = float(np.mean([x[1] for x in v]))
        sh = float(np.mean([x[2] for x in v]))
        if arm == "hp_C0":
            rows.append((LABEL[arm], len(v), ic, net, sh, None, None))
            continue
        shared = [k for k in cells[arm] if k in ctrl]
        dic, tic = paired_t([cells[arm][k][0] - ctrl[k][0] for k in shared])
        rows.append((LABEL[arm], len(v), ic, net, sh, dic, tic))

    lines = [
        "% hp_screen_table.tex -- generated by "
        "scripts/pooled/econ/hp_appendix_table.py",
        "\\begin{table*}[t]",
        "\\centering",
        "\\footnotesize",
        "\\begin{tabular}{@{}l@{\\hspace{2pt}}r@{\\hspace{2pt}}r"
        "@{\\hspace{2pt}}r@{\\hspace{2pt}}r@{}}",
        "\\toprule",
        "Configuration & rank IC & Net\\% & Sharpe & $\\Delta$IC ($t$) \\\\",
        "\\midrule",
    ]
    for name, n, ic, net, sh, dic, tic in rows:
        d = "---" if dic is None else "$%+.4f$ (%.1f)" % (dic, tic)
        lines.append("%s & $%+.4f$ & $%+.1f$ & $%.2f$ & %s \\\\"
                     % (name, ic, net, sh, d))
    lines += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\par\\smallskip",
        "{\\footnotesize",
        "All cells on the tuning span, 2016--2019, at $n{=}6$ runs each",
        "(2 panels $\\times$ 3 seeds). $\\Delta$IC is paired against the",
        "control on the cells the two share. Adoption required",
        "$\\Delta$IC $\\ge +0.0020$ at $t \\ge 2$; no cell met it, so the",
        "control configuration is the one reported in the paper.\\par}",
        "\\caption{Hyperparameter screen, every trained cell. Each varies",
        "one axis from the control.}",
        "\\label{tab:hpscreen}",
        "\\end{table*}",
    ]
    open(OUT, "w").write("\n".join(lines) + "\n")
    print("wrote %s (%d cells)" % (OUT, len(rows)))
    for r in rows:
        d = "" if r[5] is None else "  dIC %+.4f (t=%.1f)" % (r[5], r[6])
        print("  %-28s IC %+.4f  net %+6.1f  Sh %.2f%s"
              % (r[0], r[2], r[3], r[4], d))


if __name__ == "__main__":
    main()
